enabled = true
webhook_url_encrypted = "ydSXmgSYMTYShEvqkXhMr5U2UfaQQ+pxF2AJAtCu0fOOkdbbQpMoIUTaD7rIOhywwmEN695+9jkIKFwm2YmP0uXFm6AhwSdeO78A/4g/HrWwFUubgUPPPxJfBjro9dXPkei5iS2UT38f3H/4u01k6p0cC++GZOU4CA=="
username = "Pyla Support"
min_interval_seconds = 120
